/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SearchRouteImport } from './routes/search'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SongsSongIdRouteImport } from './routes/songs.$songId'
import { Route as LiveEventIdRouteImport } from './routes/live.$eventId'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSongsRouteImport } from './routes/admin.songs'
import { Route as AdminPlaylistsRouteImport } from './routes/admin.playlists'
import { Route as AdminGroupsRouteImport } from './routes/admin.groups'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminSongsNewRouteImport } from './routes/admin.songs.new'
import { Route as AdminSongsSongIdRouteImport } from './routes/admin.songs.$songId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SongsSongIdRoute = SongsSongIdRouteImport.update({
  id: '/songs/$songId',
  path: '/songs/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveEventIdRoute = LiveEventIdRouteImport.update({
  id: '/live/$eventId',
  path: '/live/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => GroupsRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSongsRoute = AdminSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlaylistsRoute = AdminPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSongsNewRoute = AdminSongsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminSongsRoute,
} as any)
const AdminSongsSongIdRoute = AdminSongsSongIdRouteImport.update({
  id: '/$songId',
  path: '/$songId',
  getParentRoute: () => AdminSongsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/collections': typeof CollectionsRoute
  '/groups': typeof GroupsRouteWithChildren
  '/search': typeof SearchRoute
  '/users': typeof UsersRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/playlists': typeof AdminPlaylistsRoute
  '/admin/songs': typeof AdminSongsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/live/$eventId': typeof LiveEventIdRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/songs/$songId': typeof AdminSongsSongIdRoute
  '/admin/songs/new': typeof AdminSongsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collections': typeof CollectionsRoute
  '/groups': typeof GroupsRouteWithChildren
  '/search': typeof SearchRoute
  '/users': typeof UsersRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/playlists': typeof AdminPlaylistsRoute
  '/admin/songs': typeof AdminSongsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/live/$eventId': typeof LiveEventIdRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/songs/$songId': typeof AdminSongsSongIdRoute
  '/admin/songs/new': typeof AdminSongsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/collections': typeof CollectionsRoute
  '/groups': typeof GroupsRouteWithChildren
  '/search': typeof SearchRoute
  '/users': typeof UsersRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/playlists': typeof AdminPlaylistsRoute
  '/admin/songs': typeof AdminSongsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/live/$eventId': typeof LiveEventIdRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/songs/$songId': typeof AdminSongsSongIdRoute
  '/admin/songs/new': typeof AdminSongsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/collections'
    | '/groups'
    | '/search'
    | '/users'
    | '/admin/events'
    | '/admin/groups'
    | '/admin/playlists'
    | '/admin/songs'
    | '/admin/users'
    | '/events/$eventId'
    | '/groups/$groupId'
    | '/live/$eventId'
    | '/songs/$songId'
    | '/admin/'
    | '/admin/songs/$songId'
    | '/admin/songs/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/collections'
    | '/groups'
    | '/search'
    | '/users'
    | '/admin/events'
    | '/admin/groups'
    | '/admin/playlists'
    | '/admin/songs'
    | '/admin/users'
    | '/events/$eventId'
    | '/groups/$groupId'
    | '/live/$eventId'
    | '/songs/$songId'
    | '/admin'
    | '/admin/songs/$songId'
    | '/admin/songs/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/collections'
    | '/groups'
    | '/search'
    | '/users'
    | '/admin/events'
    | '/admin/groups'
    | '/admin/playlists'
    | '/admin/songs'
    | '/admin/users'
    | '/events/$eventId'
    | '/groups/$groupId'
    | '/live/$eventId'
    | '/songs/$songId'
    | '/admin/'
    | '/admin/songs/$songId'
    | '/admin/songs/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CollectionsRoute: typeof CollectionsRoute
  GroupsRoute: typeof GroupsRouteWithChildren
  SearchRoute: typeof SearchRoute
  UsersRoute: typeof UsersRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  LiveEventIdRoute: typeof LiveEventIdRoute
  SongsSongIdRoute: typeof SongsSongIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/songs/$songId': {
      id: '/songs/$songId'
      path: '/songs/$songId'
      fullPath: '/songs/$songId'
      preLoaderRoute: typeof SongsSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$eventId': {
      id: '/live/$eventId'
      path: '/live/$eventId'
      fullPath: '/live/$eventId'
      preLoaderRoute: typeof LiveEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/songs': {
      id: '/admin/songs'
      path: '/songs'
      fullPath: '/admin/songs'
      preLoaderRoute: typeof AdminSongsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/playlists': {
      id: '/admin/playlists'
      path: '/playlists'
      fullPath: '/admin/playlists'
      preLoaderRoute: typeof AdminPlaylistsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/songs/new': {
      id: '/admin/songs/new'
      path: '/new'
      fullPath: '/admin/songs/new'
      preLoaderRoute: typeof AdminSongsNewRouteImport
      parentRoute: typeof AdminSongsRoute
    }
    '/admin/songs/$songId': {
      id: '/admin/songs/$songId'
      path: '/$songId'
      fullPath: '/admin/songs/$songId'
      preLoaderRoute: typeof AdminSongsSongIdRouteImport
      parentRoute: typeof AdminSongsRoute
    }
  }
}

interface AdminSongsRouteChildren {
  AdminSongsSongIdRoute: typeof AdminSongsSongIdRoute
  AdminSongsNewRoute: typeof AdminSongsNewRoute
}

const AdminSongsRouteChildren: AdminSongsRouteChildren = {
  AdminSongsSongIdRoute: AdminSongsSongIdRoute,
  AdminSongsNewRoute: AdminSongsNewRoute,
}

const AdminSongsRouteWithChildren = AdminSongsRoute._addFileChildren(
  AdminSongsRouteChildren,
)

interface AdminRouteChildren {
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminPlaylistsRoute: typeof AdminPlaylistsRoute
  AdminSongsRoute: typeof AdminSongsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventsRoute: AdminEventsRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminPlaylistsRoute: AdminPlaylistsRoute,
  AdminSongsRoute: AdminSongsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface GroupsRouteChildren {
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsGroupIdRoute: GroupsGroupIdRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CollectionsRoute: CollectionsRoute,
  GroupsRoute: GroupsRouteWithChildren,
  SearchRoute: SearchRoute,
  UsersRoute: UsersRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  LiveEventIdRoute: LiveEventIdRoute,
  SongsSongIdRoute: SongsSongIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
